// P12.4 — Statistical summary auto-report: Generate one-page reports from filtered datasets

import { getLandfalls, getStats, filterLandfalls } from './data.js';
import { categoryLabel } from './data.js';

export function generateStatisticalReport(filters) {
  const allLandfalls = getLandfalls();
  const filtered = filterLandfalls(allLandfalls, filters);
  const stats = getStats();
  
  // Build markdown report
  const title = buildFilterTitle(filters);
  const timestamp = new Date().toLocaleDateString('en-US', { 
    weekday: 'long', 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  
  // Key metrics
  const uniqueStorms = new Set(filtered.map(lf => lf.storm_id)).size;
  const deadliestStorm = findDeadliestStorm(filtered);
  const strongestStorm = findStrongestStorm(filtered);
  const earliestLandfall = filtered.length ? filtered.sort((a, b) => {
    const keyA = `${a.year}-${a.month}-${a.day}`;
    const keyB = `${b.year}-${b.month}-${b.day}`;
    return keyA.localeCompare(keyB);
  })[0] : null;
  const latestLandfall = filtered.length ? filtered.sort((a, b) => {
    const keyA = `${a.year}-${a.month}-${a.day}`;
    const keyB = `${b.year}-${b.month}-${b.day}`;
    return keyB.localeCompare(keyA);
  })[0] : null;
  
  // Monthly distribution
  const monthCounts = {};
  for (let m = 1; m <= 12; m++) monthCounts[m] = 0;
  filtered.forEach(lf => { monthCounts[lf.month]++; });
  
  // State distribution
  const stateCounts = {};
  filtered.forEach(lf => {
    if (lf.state) stateCounts[lf.state] = (stateCounts[lf.state] || 0) + 1;
  });
  const topStates = Object.entries(stateCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);
  
  // Category distribution
  const catCounts = {};
  filtered.forEach(lf => {
    const cat = lf.category <= 0 ? 'TS' : String(lf.category);
    catCounts[cat] = (catCounts[cat] || 0) + 1;
  });
  
  const markdown = `# Hurricane Landfall Summary Report

**Report Date:** ${timestamp}  
**Data Source:** NOAA NHC HURDAT2 Best-Track Database  
**GitHub:** https://github.com/SysAdminDoc/HurricaneMap

---

## Filter Summary

${title}

---

## Key Metrics

| Metric | Value |
|--------|-------|
| **Total Landfalls** | ${filtered.length} |
| **Unique Storms** | ${uniqueStorms} |
| **Year Range** | ${filters.yearMin}–${filters.yearMax} |
| **Strongest Wind** | ${strongestStorm ? strongestStorm.wind + ' kt' : 'N/A'} |
| **Deadliest Storm** | ${deadliestStorm ? deadliestStorm.name + ' (' + deadliestStorm.year + ')' : 'N/A'} |

---

## Temporal Distribution

### By Month
${formatMonthChart(monthCounts, filtered.length)}

### Date Range
- **Earliest:** ${earliestLandfall ? `${monthName(earliestLandfall.month)} ${earliestLandfall.day}, ${earliestLandfall.year}` : 'N/A'}
- **Latest:** ${latestLandfall ? `${monthName(latestLandfall.month)} ${latestLandfall.day}, ${latestLandfall.year}` : 'N/A'}

---

## Geographic Distribution

### Top 5 States
${topStates.map(([state, count]) => `- **${state}** — ${count} landfall${count === 1 ? '' : 's'}`).join('\n')}

---

## Intensity Distribution

### By Saffir-Simpson Category
${Object.entries(catCounts)
  .sort(([a], [b]) => {
    const aNum = a === 'TS' ? -1 : parseInt(a);
    const bNum = b === 'TS' ? -1 : parseInt(b);
    return aNum - bNum;
  })
  .map(([cat, count]) => `- **${cat === 'TS' ? 'Tropical Storm' : 'Category ' + cat}** — ${count} (${Math.round(count / filtered.length * 100)}%)`)
  .join('\n')}

---

## Data Source & Attribution

Historical hurricane landfall data sourced from **NOAA's National Hurricane Center HURDAT2 best-track database** (https://www.nhc.noaa.gov/data/).

**Citation:** Landsea, C. W., and J. L. Franklin, 2013: The Atlantic Hurricane Database Re-analysis Project: Documentation for the 1851–2012 Alterations and Additions to the HURDAT2 Database. NOAA Technical Memorandum NWS NHC-7.

### Methodology Notes

- **Landfalls** are identified as points where the cyclone center crosses a U.S. state boundary or coastline (HURDAT2 \`L\` marker or inferred via point-in-polygon).
- **Categories** assigned by Saffir-Simpson scale based on maximum sustained winds at landfall.
- **Wind Speed** recorded in knots (kt); conversion to mph: kt × 1.15078.
- **Pre-1945 data** is less accurate due to pre-aircraft reconnaissance; pre-satellite (pre-1960s) data should be interpreted with caution.

---

**Report Generated by HurricaneMap** — https://github.com/SysAdminDoc/HurricaneMap
`;

  return {
    markdown,
    title: `Hurricane-Summary-${new Date().toISOString().split('T')[0]}`,
  };
}

function buildFilterTitle(filters) {
  const parts = [];
  
  if (filters.yearMin !== 1851 || filters.yearMax !== 2025) {
    parts.push(`Years ${filters.yearMin}–${filters.yearMax}`);
  }
  
  if (filters.categories.size < 6) {
    const cats = Array.from(filters.categories).sort((a, b) => {
      const aNum = a === 'ts' ? -1 : parseInt(a);
      const bNum = b === 'ts' ? -1 : parseInt(b);
      return aNum - bNum;
    }).map(c => c === 'ts' ? 'Tropical Storm' : 'Cat ' + c);
    parts.push(`Categories: ${cats.join(', ')}`);
  }
  
  if (filters.state) {
    parts.push(`State: ${filters.state}`);
  }
  
  if (parts.length === 0) {
    return 'All landfalls (1851–2025, all categories, all states)';
  }
  
  return parts.join(' • ');
}

function monthName(m) {
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return months[m - 1] || '';
}

function formatMonthChart(counts, total) {
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const lines = [];
  
  for (let i = 1; i <= 12; i++) {
    const count = counts[i] || 0;
    const pct = total > 0 ? Math.round(count / total * 100) : 0;
    const bar = '█'.repeat(Math.round(count / 3)); // scale to fit
    lines.push(`- **${months[i - 1]}** — ${count} (${pct}%) ${bar}`);
  }
  
  return lines.join('\n');
}

function findDeadliestStorm(landfalls) {
  // This would need impacts data to be properly implemented
  // For now, return the first landfall
  return landfalls.length > 0 ? landfalls[0] : null;
}

function findStrongestStorm(landfalls) {
  let strongest = null;
  let maxWind = 0;
  
  for (const lf of landfalls) {
    if (lf.wind && lf.wind > maxWind) {
      maxWind = lf.wind;
      strongest = lf;
    }
  }
  
  return strongest;
}

export function downloadReportAsText(markdown, filename) {
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', filename + '.md');
  link.style.visibility = 'hidden';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export { generateStatisticalReport };
